files = [
    'stream/taymckenzienzbs_male_p.rpf/*',
    'stream/taymckenzienzbs_male.rpf/*',
    'stream/taymckenzienzbs_female_p.rpf/*',
    'stream/taymckenzienzbs_female.rpf/*',
    'stream/creaturemetadata.rpf/*'
]

[meta]
'stream/mp_m_freemode_01_mp_m_taymckenzienzbs.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/mp_f_freemode_01_mp_f_taymckenzienzbs.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/pedalternatevariations.meta' = 'ALTERNATE_VARIATIONS_FILE'